build Docker image buildmaster:
  stage: docker
  extends: .build Docker image

test Docker image buildmaster:
  stage: docker test
  extends: .docker in docker
  needs: ["build Docker image buildmaster"]
  script:
    - export IMAGE_NAME="$(echo $CI_JOB_NAME | sed 's/test Docker image \(.*\)/\1/')"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull "$CI_REGISTRY_IMAGE/$IMAGE_NAME-$BUILDBOT_VERSION:$CI_COMMIT_REF_SLUG"
    - >
      docker run --rm "$CI_REGISTRY_IMAGE/$IMAGE_NAME-$BUILDBOT_VERSION:$CI_COMMIT_REF_SLUG" |
      grep "buildmaster configured in /master"

deploy Docker image buildmaster:
  stage: docker deploy
  extends: .deploy Docker image
  needs: ["test Docker image buildmaster"]
